### ISSUE TITLE
"handlerFunc is not a function" error thrown when trying to handle a valid path with unimplemented metho

### ISSUE THREAD

**Issue by austinkelleher** [charlieduong94/koa-path-router#2]
For example, the following path has been registered:

```
GET /api/hello
```

And a request is made with an unimplemented method:

```
POST /api/hello
```

The following error is thrown:

```
  TypeError: handlerFunc is not a function
      at RouteHandler.handleRequest (/koa-path-router/src/RouteHandler.js:31:12)
      at /koa-path-router/src/Router.js:117:40
      at dispatch (/koa-path-router/node_modules/koa-compose/index.js:42:32)
      at //koa-path-router/node_modules/koa-compose/index.js:34:12
      at Server.handleRequest (/koa-path-router/node_modules/koa/lib/application.js:136:14)
      at emitTwo (events.js:125:13)
      at Server.emit (events.js:213:7)
      at parserOnIncoming (_http_server.js:602:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
```

**Comment by ctdio** [comment]
Published `0.1.1`
